version: "3.9"
services:
  sftpgo:
    image: drakkan/sftpgo:latest
    environment: [ "SFTPGO_WEBSERVER__BINDINGS__0__PORT=8086" ]
    ports: ["2022:2022","8086:8086"]
    volumes: ["./sftp-data:/srv/sftpgo/data"]
  nifi:
    image: apache/nifi:1.27.0
    ports: ["8087:8080"]
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - ./nifi/template:/opt/nifi/nifi-current/conf/templates
